services:
  - type: web
    name: spring-boot-backend
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile   # 👈 points to backend Dockerfile
    autoDeploy: true
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        value: ${DATABASE_URL}   # 👈 Render injects this from your Postgres service
      - key: SPRING_DATASOURCE_USERNAME
        value: ${DATABASE_USERNAME}
      - key: SPRING_DATASOURCE_PASSWORD
        value: ${DATABASE_PASSWORD}
